config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  get "/projects", to: "static_pages#projects"
  get "/skills", to: "static_pages#skills"
  get "/tools", to: "static_pages#tools"

  put "/switch_locale", to: "locales#switch"

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    session[:locale] = params[:locale] if params[:locale].present?
    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController
  def switch
    session[:locale] = params[:locale]
    I18n.locale = session[:locale]

    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @current_page = t(:label_home)
  end

  def about
    @current_page = t(:label_about)
  end

  def articles
  end

  def projects
    @current_page = t(:label_projects)
  end

  def skills
    @current_page = t(:label_skills)
  end

  def tools
    @current_page = t(:label_tools)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def happy_birthday_day?
    Date.current.day == 15 && Date.current.month == 3
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_article.html.erb
<article class="md:grid md:grid-cols-4 md:items-baseline">
  <div class="md:col-span-3 group relative flex flex-col items-start">
    <h2 class="text-base font-semibold tracking-tight text-zinc-800 dark:text-zinc-100">
      <div class="absolute -inset-x-4 -inset-y-6 z-0 scale-95 bg-zinc-50 opacity-0 transition group-hover:scale-100 group-hover:opacity-100 dark:bg-zinc-800/50 sm:-inset-x-6 sm:rounded-2xl"></div>
      <a href="/articles/crafting-a-design-system-for-a-multiplanetary-future"><span class="absolute -inset-x-4 -inset-y-6 z-20 sm:-inset-x-6 sm:rounded-2xl"></span><span class="relative z-10">Crafting a design system for a multiplanetary future</span></a>
    </h2>
    <time class="md:hidden relative z-10 order-first mb-3 flex items-center text-sm text-zinc-400 dark:text-zinc-500 pl-3.5" datetime="2022-09-05">
      <span class="absolute inset-y-0 left-0 flex items-center" aria-hidden="true"><span class="h-4 w-0.5 rounded-full bg-zinc-200 dark:bg-zinc-500"></span></span>September
      5, 2022
    </time>
    <p class="relative z-10 mt-2 text-sm text-zinc-600 dark:text-zinc-400">Most companies try to stay
      ahead of the curve when it comes to visual design, but for Planetaria we needed to create a brand
      that would still inspire us 100 years from now when humanity has spread across our entire solar
      system.</p>
    <div aria-hidden="true" class="relative z-10 mt-4 flex items-center text-sm font-medium text-teal-500">Read
      article
      <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="ml-1 h-4 w-4 stroke-current">
        <path d="M6.75 5.75 9.25 8l-2.5 2.25" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
      </svg>
    </div>
  </div>
  <time class="mt-1 hidden md:block relative z-10 order-first mb-3 flex items-center text-sm text-zinc-400 dark:text-zinc-500" datetime="2022-09-05">September
    5, 2022
  </time>
</article>

app/views/articles/index.html.erb
<div class="sm:px-8 mt-4 sm:mt-8">
  <div class="mx-auto w-full max-w-7xl lg:px-8">
    <div class="relative px-4 sm:px-8 lg:px-12">
      <div class="mx-auto max-w-2xl lg:max-w-5xl">
        <header class="max-w-2xl">
          <h1 class="text-4xl font-bold tracking-tight text-zinc-800 dark:text-zinc-100 sm:text-5xl">Текста, которыми
          мне бы хотелось поделиться.</h1>
          <p class="mt-6 text-base text-zinc-600 dark:text-zinc-400">
            Здесь представлены профильные обучающие статьи, которые помогут не терять время на изобретение собственного
            велосипеда. Все материалы указаны с автором исходной статьи, если он у нее имеется.
          </p>
        </header>
        <div class="mt-16 sm:mt-20">
          <div class="md:border-l md:border-zinc-100 md:pl-6 md:dark:border-zinc-700/40">
            <div class="flex max-w-3xl flex-col space-y-16">
              <article class="md:grid md:grid-cols-4 md:items-baseline">
                <div class="md:col-span-3 group relative flex flex-col items-start">
                  <h2 class="text-base font-semibold tracking-tight text-zinc-800 dark:text-zinc-100">
                    <div class="absolute -inset-x-4 -inset-y-6 z-0 scale-95 bg-zinc-50 opacity-0 transition group-hover:scale-100 group-hover:opacity-100 dark:bg-zinc-800/50 sm:-inset-x-6 sm:rounded-2xl"></div>
                    <a href="/articles/crafting-a-design-system-for-a-multiplanetary-future"><span class="absolute -inset-x-4 -inset-y-6 z-20 sm:-inset-x-6 sm:rounded-2xl"></span><span class="relative z-10">Crafting a design system for a multiplanetary future</span></a>
                  </h2>
                  <time class="md:hidden relative z-10 order-first mb-3 flex items-center text-sm text-zinc-400 dark:text-zinc-500 pl-3.5" datetime="2022-09-05">
                    <span class="absolute inset-y-0 left-0 flex items-center" aria-hidden="true"><span class="h-4 w-0.5 rounded-full bg-zinc-200 dark:bg-zinc-500"></span></span>September
                    5, 2022
                  </time>
                  <p class="relative z-10 mt-2 text-sm text-zinc-600 dark:text-zinc-400">Most companies try to stay
                    ahead of the curve when it comes to visual design, but for Planetaria we needed to create a brand
                    that would still inspire us 100 years from now when humanity has spread across our entire solar
                    system.</p>
                  <div aria-hidden="true" class="relative z-10 mt-4 flex items-center text-sm font-medium text-teal-500">Read
                    article
                    <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="ml-1 h-4 w-4 stroke-current">
                      <path d="M6.75 5.75 9.25 8l-2.5 2.25" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>
                  </div>
                </div>
                <time class="mt-1 hidden md:block relative z-10 order-first mb-3 flex items-center text-sm text-zinc-400 dark:text-zinc-500" datetime="2022-09-05">September
                  5, 2022
                </time>
              </article>
              <article class="md:grid md:grid-cols-4 md:items-baseline">
                <div class="md:col-span-3 group relative flex flex-col items-start">
                  <h2 class="text-base font-semibold tracking-tight text-zinc-800 dark:text-zinc-100">
                    <div class="absolute -inset-x-4 -inset-y-6 z-0 scale-95 bg-zinc-50 opacity-0 transition group-hover:scale-100 group-hover:opacity-100 dark:bg-zinc-800/50 sm:-inset-x-6 sm:rounded-2xl"></div>
                    <a href="/articles/introducing-animaginary"><span class="absolute -inset-x-4 -inset-y-6 z-20 sm:-inset-x-6 sm:rounded-2xl"></span><span class="relative z-10">Introducing Animaginary: High performance web animations</span></a>
                  </h2>
                  <time class="md:hidden relative z-10 order-first mb-3 flex items-center text-sm text-zinc-400 dark:text-zinc-500 pl-3.5" datetime="2022-09-02">
                    <span class="absolute inset-y-0 left-0 flex items-center" aria-hidden="true"><span class="h-4 w-0.5 rounded-full bg-zinc-200 dark:bg-zinc-500"></span></span>September
                    2, 2022
                  </time>
                  <p class="relative z-10 mt-2 text-sm text-zinc-600 dark:text-zinc-400">When you’re building a website
                    for a company as ambitious as Planetaria, you need to make an impression. I wanted people to visit
                    our website and see animations that looked more realistic than reality itself.</p>
                  <div aria-hidden="true" class="relative z-10 mt-4 flex items-center text-sm font-medium text-teal-500">Read
                    article
                    <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="ml-1 h-4 w-4 stroke-current">
                      <path d="M6.75 5.75 9.25 8l-2.5 2.25" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>
                  </div>
                </div>
                <time class="mt-1 hidden md:block relative z-10 order-first mb-3 flex items-center text-sm text-zinc-400 dark:text-zinc-500" datetime="2022-09-02">September
                  2, 2022
                </time>
              </article>
              <article class="md:grid md:grid-cols-4 md:items-baseline">
                <div class="md:col-span-3 group relative flex flex-col items-start">
                  <h2 class="text-base font-semibold tracking-tight text-zinc-800 dark:text-zinc-100">
                    <div class="absolute -inset-x-4 -inset-y-6 z-0 scale-95 bg-zinc-50 opacity-0 transition group-hover:scale-100 group-hover:opacity-100 dark:bg-zinc-800/50 sm:-inset-x-6 sm:rounded-2xl"></div>
                    <a href="/articles/rewriting-the-cosmos-kernel-in-rust"><span class="absolute -inset-x-4 -inset-y-6 z-20 sm:-inset-x-6 sm:rounded-2xl"></span><span class="relative z-10">Rewriting the cosmOS kernel in Rust</span></a>
                  </h2>
                  <time class="md:hidden relative z-10 order-first mb-3 flex items-center text-sm text-zinc-400 dark:text-zinc-500 pl-3.5" datetime="2022-07-14">
                    <span class="absolute inset-y-0 left-0 flex items-center" aria-hidden="true"><span class="h-4 w-0.5 rounded-full bg-zinc-200 dark:bg-zinc-500"></span></span>July
                    14, 2022
                  </time>
                  <p class="relative z-10 mt-2 text-sm text-zinc-600 dark:text-zinc-400">When we released the first
                    version of cosmOS last year, it was written in Go. Go is a wonderful programming language, but it’s
                    been a while since I’ve seen an article on the front page of Hacker News about rewriting some
                    important tool in Go and I see articles on there about rewriting things in Rust every single
                    week.</p>
                  <div aria-hidden="true" class="relative z-10 mt-4 flex items-center text-sm font-medium text-teal-500">Read
                    article
                    <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="ml-1 h-4 w-4 stroke-current">
                      <path d="M6.75 5.75 9.25 8l-2.5 2.25" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>
                  </div>
                </div>
                <time class="mt-1 hidden md:block relative z-10 order-first mb-3 flex items-center text-sm text-zinc-400 dark:text-zinc-500" datetime="2022-07-14">July
                  14, 2022
                </time>
              </article>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="mt-32 flex-none">
  <div class="sm:px-8">
    <div class="mx-auto w-full max-w-7xl lg:px-8">
      <div class="border-t border-zinc-100 pb-16 pt-10 dark:border-zinc-700/40">
        <div class="relative px-4 sm:px-8 lg:px-12">
          <div class="mx-auto max-w-2xl lg:max-w-5xl">
            <div class="flex flex-col items-center justify-between gap-6 sm:flex-row">
              <div class="flex flex-wrap justify-center gap-x-6 gap-y-1 text-sm font-medium text-zinc-800 dark:text-zinc-200">
                <%= link_to root_path, class: "transition hover:text-teal-500 dark:hover:text-teal-400" do %>
                  <%= t(:label_home) %>
                <% end %>
                <%= link_to projects_path, class: "transition hover:text-teal-500 dark:hover:text-teal-400" do %>
                  <%= t(:label_projects) %>
                <% end %>
                <%= link_to skills_path, class: "transition hover:text-teal-500 dark:hover:text-teal-400" do %>
                  <%= t(:label_skills) %>
                <% end %>
                <%= link_to tools_path, class: "transition hover:text-teal-500 dark:hover:text-teal-400" do %>
                  <%= t(:label_tools) %>
                <% end %>
              </div>
              <p class="text-sm text-zinc-400 dark:text-zinc-500">
                © <!-- --><%= Time.now.year %><!-- -->
                <%= t(:label_name_and_surname) %>
              </p></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="pointer-events-none relative z-50 flex flex-none flex-col">
  <div class="order-last mt-[calc(theme(spacing.16)-theme(spacing.3))]"></div>
  <div class="top-0 order-last -mb-3 pt-3 sm:px-8">
    <div class="mx-auto w-full max-w-7xl lg:px-8">
      <div class="relative px-4 sm:px-8 lg:px-12">
        <div class="mx-auto max-w-2xl lg:max-w-5xl">
          <div class="top-[var(--avatar-top,theme(spacing.3))] w-full">
            <div class="relative">
              <div class="absolute top-3 left-0 h-10 w-10 origin-left rounded-full bg-white/90 shadow-lg shadow-zinc-800/5 ring-1 ring-zinc-900/5 backdrop-blur transition-opacity p-0.5 dark:bg-zinc-800/90 dark:ring-white/10" style="opacity:var(--avatar-border-opacity, 0);transform:var(--avatar-border-transform)"></div>
              <a aria-label="Home" class="pointer-events-auto block h-16 w-16 origin-left" href="/">
                <%= image_tag "avatar.jpg", class: "rounded-full bg-zinc-100 object-cover dark:bg-zinc-800 h-16 w-16" %>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="top-0 z-10 h-16 pt-6">
    <div class="sm:px-8 top-[var(--header-top,theme(spacing.6))] w-full">
      <div class="mx-auto w-full max-w-7xl lg:px-8">
        <div class="relative px-4 sm:px-8 lg:px-12">
          <div class="mx-auto max-w-2xl lg:max-w-5xl">
            <div class="relative flex gap-4">
              <div class="flex flex-1 justify-start">
                <div class="pointer-events-auto" data-headlessui-state="">
                  <% if session[:locale].present? && session[:locale] == "en" %>
                    <%= button_to switch_locale_path(locale: "ru"), method: :put, class: "group rounded-full bg-white/90 px-3 py-2 shadow-lg shadow-zinc-800/5 ring-1 ring-zinc-900/5 backdrop-blur transition dark:bg-zinc-800/90 dark:ring-white/10 dark:hover:ring-white/20" do %>
                      <%= image_tag "flags/ru.png", class: "h-7 w-7" %>
                    <% end %>
                  <% else %>
                    <%= button_to switch_locale_path(locale: "en"), method: :put, class: "group rounded-full bg-white/90 px-3 py-2 shadow-lg shadow-zinc-800/5 ring-1 ring-zinc-900/5 backdrop-blur transition dark:bg-zinc-800/90 dark:ring-white/10 dark:hover:ring-white/20" do %>
                      <%= image_tag "flags/gb.png", class: "h-7 w-7" %>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="flex flex-1 justify-end md:justify-center">
                <div class="pointer-events-auto md:hidden" data-headlessui-state="">
                  <div class="dropdown dropdown-end">
                    <div tabindex="0" role="button" class="ml-3 h-7 w-7 stroke-zinc-500 group-hover:stroke-zinc-700 dark:group-hover:stroke-zinc-400">
                      <svg viewBox="0 0 8 6" aria-hidden="true" class="ml-3 h-7 w-7 stroke-zinc-500 group-hover:stroke-zinc-700 dark:group-hover:stroke-zinc-400">
                        <path d="M1.75 1.75 4 4.25l2.25-2.5" fill="none" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                      </svg>
                    </div>
                    <ul tabindex="0" class="w-52 p-2 shadow dropdown-content z-[1] menu bg-base-100 rounded-box">
                      <li><%= link_to root_path, class: "relative whitespace-nowrap block px-3 py-2 transition hover:text-teal-500 dark:hover:text-teal-400" do %>
                          <%= t(:label_home) %>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to projects_path, class: "relative whitespace-nowrap block px-3 py-2 transition hover:text-teal-500 dark:hover:text-teal-400" do %>
                          <%= t(:label_projects) %>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to skills_path, class: "relative whitespace-nowrap block px-3 py-2 transition hover:text-teal-500 dark:hover:text-teal-400" do %>
                          <%= t(:label_skills) %>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to tools_path, class: "relative whitespace-nowrap block px-3 py-2 transition hover:text-teal-500 dark:hover:text-teal-400" do %>
                          <%= t(:label_tools) %>
                        <% end %>
                      </li>
                    </ul>
                  </div>
                </div>
                <div style="position:fixed;top:1px;left:1px;width:1px;height:0;padding:0;margin:-1px;overflow:hidden;clip:rect(0, 0, 0, 0);white-space:nowrap;border-width:0;display:none"></div>
                <nav class="pointer-events-auto hidden md:block">
                  <ul class="flex rounded-full bg-white/90 px-3 text-sm font-medium text-zinc-800 shadow-lg shadow-zinc-800/5 ring-1 ring-zinc-900/5 backdrop-blur dark:bg-zinc-800/90 dark:text-zinc-200 dark:ring-white/10">
                    <li>
                      <%#= link_to articles_path, class: "relative whitespace-nowrap block px-3 py-2 transition hover:text-teal-500 dark:hover:text-teal-400" do %>
                      <%#= t(:label_articles) %>
                      <%# end %>
                      <% if current_page?(root_path) %>
                        <%= link_to root_path, class: "relative block px-3 py-2 transition text-teal-500 dark:text-teal-400" do %>
                          <%= t(:label_home) %>
                          <span class="absolute inset-x-1 -bottom-px h-px bg-gradient-to-r from-teal-500/0 via-teal-500/40 to-teal-500/0 dark:from-teal-400/0 dark:via-teal-400/40 dark:to-teal-400/0"></span>
                        <% end %>
                      <% else %>
                        <%= link_to root_path, class: "relative whitespace-nowrap block px-3 py-2 transition hover:text-teal-500 dark:hover:text-teal-400" do %>
                          <%= t(:label_home) %>
                        <% end %>
                      <% end %>
                    </li>
                    <li>
                      <% if current_page?(projects_path) %>
                        <%= link_to projects_path, class: "relative block px-3 py-2 transition text-teal-500 dark:text-teal-400" do %>
                          <%= t(:label_projects) %>
                          <span class="absolute inset-x-1 -bottom-px h-px bg-gradient-to-r from-teal-500/0 via-teal-500/40 to-teal-500/0 dark:from-teal-400/0 dark:via-teal-400/40 dark:to-teal-400/0"></span>
                        <% end %>
                      <% else %>
                        <%= link_to projects_path, class: "relative whitespace-nowrap block px-3 py-2 transition hover:text-teal-500 dark:hover:text-teal-400" do %>
                          <%= t(:label_projects) %>
                        <% end %>
                      <% end %>
                    </li>
                    <li>
                      <% if current_page?(skills_path) %>
                        <%= link_to skills_path, class: "relative block px-3 py-2 transition text-teal-500 dark:text-teal-400" do %>
                          <%= t(:label_skills) %>
                          <span class="absolute inset-x-1 -bottom-px h-px bg-gradient-to-r from-teal-500/0 via-teal-500/40 to-teal-500/0 dark:from-teal-400/0 dark:via-teal-400/40 dark:to-teal-400/0"></span>
                        <% end %>
                      <% else %>
                        <%= link_to skills_path, class: "relative whitespace-nowrap block px-3 py-2 transition hover:text-teal-500 dark:hover:text-teal-400" do %>
                          <%= t(:label_skills) %>
                        <% end %>
                      <% end %>
                    </li>
                    <li>
                      <% if current_page?(tools_path) %>
                        <%= link_to skills_path, class: "relative block px-3 py-2 transition text-teal-500 dark:text-teal-400" do %>
                          <%= t(:label_tools) %>
                          <span class="absolute inset-x-1 -bottom-px h-px bg-gradient-to-r from-teal-500/0 via-teal-500/40 to-teal-500/0 dark:from-teal-400/0 dark:via-teal-400/40 dark:to-teal-400/0"></span>
                        <% end %>
                      <% else %>
                        <%= link_to tools_path, class: "relative whitespace-nowrap block px-3 py-2 transition hover:text-teal-500 dark:hover:text-teal-400" do %>
                          <%= t(:label_tools) %>
                        <% end %>
                      <% end %>
                    </li>
                  </ul>
                </nav>
              </div>
              <div class="flex justify-end md:flex-1">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
<head>
  <title><%= "#{@current_page} | " if @current_page.present?%><%= t(:label_name_and_surname)%></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_importmap_tags %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<body class="flex h-full bg-zinc-50 dark:bg-black">
<div class="flex w-full">
  <div class="fixed inset-0 flex justify-center sm:px-8">
    <div class="flex w-full max-w-7xl lg:px-8">
      <div class="w-full bg-white ring-1 ring-zinc-100 dark:bg-zinc-900 dark:ring-zinc-300/20"></div>
    </div>
  </div>
  <div class="relative flex w-full flex-col">
    <%= render partial: 'layouts/header' %>
    <main class="flex-auto">
      <%= yield %>
    </main>

    <%= render partial: 'layouts/footer' %>
  </div>
</div>
</body>
</html>

app/views/static_pages/index.html.erb
<div class="mt-9 sm:px-8">
  <div class="mx-auto w-full max-w-7xl lg:px-8">
    <div class="relative px-4 sm:px-8 lg:px-12">
      <div class="mx-auto max-w-2xl lg:max-w-5xl">
        <div class="max-w-2xl">
          <%= render partial: "static_pages/index_sections/hero" %>

          <div class="mt-10 flex gap-6">
            <%= render partial: "static_pages/index_sections/social_media" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="mt-16 sm:mt-20">
  <div class="-my-4 flex justify-center gap-5 overflow-hidden py-4 sm:gap-8">
    <%= render partial: "static_pages/index_sections/posters" %>
  </div>
</div>

<div class="mt-24 sm:px-8 md:mt-28">
  <div class="mx-auto w-full max-w-7xl lg:px-8">
    <div class="relative px-4 sm:px-8 lg:px-12">
      <div class="mx-auto max-w-2xl lg:max-w-5xl">
        <div class="mx-auto grid max-w-xl grid-cols-1 gap-y-20 lg:max-w-none lg:grid-cols-2">
          <div class="flex flex-col gap-16">
            <%= render partial: "static_pages/index_sections/job_offer" %>
          </div>

          <div class="space-y-10 lg:pl-16 xl:pl-24">
            <div class="rounded-2xl border border-zinc-200 p-6 dark:border-zinc-700/40">
              <%= render partial: "static_pages/index_sections/experience" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/index_sections/_experience_item.html.erb
<li class="flex items-center gap-4 rounded-md p-2 hover:bg-zinc-100">
  <div class="relative mt-1 flex h-10 w-10 flex-none items-center justify-center rounded-full bg-white dark:bg-zinc-800">
    <% if icon_image.present? %>
      <%= image_tag icon_image, class: icon_class %>
    <% elsif icon_svg.present? %>
      <%= inline_svg icon_svg, class: icon_class %>
    <% end %>
  </div>
  <dl class="flex flex-auto flex-wrap gap-x-2">
    <dt class="sr-only">Company</dt>
    <dd class="w-full flex-none text-sm font-medium text-zinc-900 dark:text-zinc-100"><%= company %></dd>

    <dt class="sr-only">Role</dt>
    <dd class="text-xs text-zinc-500 dark:text-zinc-400"><%= role %></dd>

    <dt class="sr-only">Date</dt>
    <dd class="ml-auto text-xs text-zinc-400 dark:text-zinc-500" aria-label="<%= aria_label %>">
      <time datetime="<%= date_from %>"><%= date_from %></time>
      <% if date_to.present? %>
        <span aria-hidden="true">—</span>
        <time datetime="<%= date_to %>"><%= date_to %></time>
      <% else %>
        <span aria-hidden="true">—</span>
        <time><%= t(:label_current_time) %></time>
      <% end %>
    </dd>
  </dl>
</li>

app/views/static_pages/index_sections/_hero.html.erb
<% if happy_birthday_day? %>
  <div class="mb-4 flex flex-col items-center justify-center gap-3">
    <%= image_tag "secrets/happy-birthday.webp" %>
    <p class="mt-4 text-base text-zinc-600 dark:text-zinc-400">С днем рождения тебя. Даже если ты это не видишь и не читаешь.</p>
  </div>
<% else %>
  <h1 class="text-4xl font-bold tracking-tight text-zinc-800 dark:text-zinc-100 sm:text-5xl">
    <%= t(:label_header_description) %>
  </h1>
  <p class="mt-6 text-base text-zinc-600 dark:text-zinc-400">
    <%= t(:label_body_description_1) %>
  </p>
  <p class="mt-2 text-base text-zinc-600 dark:text-zinc-400">
    <%= t(:label_body_description_2) %>
  </p>
<% end %>

app/views/static_pages/index_sections/_job_offer.html.erb
<form class="rounded-2xl border border-zinc-200 p-6 dark:border-zinc-700/40" action="/thank-you">
  <h2 class="flex text-sm font-semibold text-zinc-900 dark:text-zinc-100">
    <%= inline_svg "mail.svg", class: "size-6" %>
    <span class="ml-3">
      <%= t(:label_heading_job_offers) %>
    </span>
  </h2>
  <p class="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
    <%= t(:label_active_body_job_offers) %>
  </p>
  <div class="mt-6 flex">
    <%= mail_to "nedprofit@gmail.com", class: "inline-flex items-center gap-x-1.5 rounded-full bg-gray-100 px-2 py-1 text-xs font-medium text-gray-600" do %>
      <svg class="fill-green-500 h-1.5 w-1.5" viewBox="0 0 6 6" aria-hidden="true">
        <circle cx="3" cy="3" r="3"/>
      </svg>
      nedprofit@gmail.com
    <% end %>
  </div>
</form>